name: Test CLI Install Across Operating Systems

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-command:
    name: Test Install Command
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Install Command
      # curl -sSfL https://raw.githubusercontent.com/omni-network/omni/main/scripts/install_omni_cli.sh | sh -s
      run: |
        bash scripts/install_omni_cli.sh 
      shell: bash

    - name: Confirm Installation Location
      run: |
        ls -la ~/bin

    - name: Check Installation
      run: |
        export PATH=$PATH:~/bin
        omni version
      shell: bash
