name: Test CLI Install Across Operating Systems

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-command:
    name: Test Install Command
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Install Command
      run: |
        curl -sSfL https://raw.githubusercontent.com/omni-network/omni/main/scripts/install_omni_cli.sh | sh -s
      shell: bash

    - name: Add to PATH
      run: |
        echo "export PATH=\$PATH:~/bin" >> ~/.bashrc
      shell: bash

    - name: Check Installation
      run: |
        omni --version
      shell: bash
